overlay = "."
crate_src_path = ".."
maintainer = "Proxmox Support Team <support@proxmox.com>"

[source]
vcs_git = "git://git.proxmox.com/git/ui/proxmox-yew-comp.git"
vcs_browser = "https://git.proxmox.com/?p=ui/proxmox-yew-comp.git"
